export default (theme) => ({
  container: {
    width: "100%",
    minHeight: 600,
    backgroundColor: theme.palette.common.white,
  },
  banner: {
    backgroundColor: "#1E212E",
    position: "relative",
    height: "340px",
    backgroundSize: "cover",
    width: "100%",
    // marginTop: "-8px",
    backgroundPosition: "center",
  },
  bannerMask: {
    maxWidth: 1200,
    minWidth: 1040,
    margin: "0 auto",
    height: "calc(100% - 60px)",
  },
  pic: {
    width: "100%",
    height: "100%",
    "& >div": {
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center center",
      backgroundSize: "cover",
      minWidth: 1040,
      maxWidth: 1200,
      height: "calc(100% - 60px)",
      margin: "0 auto",
    },
  },
  absolute: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "calc(100% - 60px)",
  },
  bannerContent: {
    // backgroundImage:
    //   "radial-gradient(circle farthest-corner at 70% 50%, rgba(35, 37, 54, 0) 22%, #1e212e 44%)",
    maxWidth: 1200,
    minWidth: 1040,
    margin: "0 auto",
    display: "flex",
    width: "100%",
    height: "100%",
    flexDirection: "column",
    justifyContent: "center",
    color: theme.palette.common.white,
    "& h2": { fontSize: "48px", lineHeight: "70px" },
    "& p": {
      marginTop: 10,
      fontSize: 24,
      lineHeight: "35px",
    },
  },
  line: {
    marginTop: "15px",
    marginBottom: "3%",
    "&>h4": {
      borderRadius: "40px",
      padding: "5px 27px",
      border: `1px solid ${theme.palette.primary.contrastText}`,
      float: "left",
      margin: "0 18px",
      lineHeight: "20px",
    },
  },
  button: {
    color: theme.palette.primary.contrastText,
    borderColor: theme.palette.primary.contrastText,
    padding: "5px 32px",
    "&:hover": {
      borderColor: theme.palette.primary.contrastText,
    },
  },
  list: {
    marginBottom: 20,
    background: theme.palette.common.white,
  },
  coinplusList: {
    width: "100%",
    maxWidth: 1200,
    minWidth: 1040,
    margin: "0 auto",
    overflow: "auto",
    "& h2": {
      margin: "30px 0 20px",
      fontSize: 20,
      lineHeight: "29px",
      fontWeight: "bold",
    },
  },
  listNav: {
    height: 60,
    background: "rgba(42,44,55, 0.8)",
    color: theme.palette.common.white,
    border: "1px solid #434554",
    marginTop: -60,
    position: "relative",
    "& ul": {
      ...theme.typography.body1,
      maxWidth: 1200,
      minWidth: 1040,
      margin: "0 auto",
      display: "flex",
      height: "100%",
      alignItems: "center",
      "& li": {
        margin: "0 60px 0 0",
        cursor: "pointer",
        "&:hover": {
          color: theme.palette.primary.main,
        },
      },
    },
  },
});
