// 全局的布局style
export default (theme) => ({
  preview: {
    width: "100%",
    minWidth: 1200,
    background: theme.palette.error.main,
    "& div": {
      width: 1200,
      margin: "0 auto",
      height: 30,
      lineHeight: 1,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      color: theme.palette.common.white,
    },
    "& i": {
      color: theme.palette.common.white,
      cursor: "pointer",
    },
  },
  g_headerBox: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  g_contentbox: {
    margin: 0,
    width: "100%",
    minHeight: "calc(100vh - 312px)",
  },
  g_contentbox_q: {
    margin: 0,
    background: theme.palette2.grey[700],
  },
  g_guild: {
    margin: "0 auto",
    width: 1200,
  },
  download_layer: {
    position: "fixed",
    background: theme.palette.background.default,
    left: 0,
    bottom: 0,
    height: 200,
    width: "100%",
    zIndex: 1990,
    boxShadow: theme.shadows[1],
    display: "flex",
    alignItems: "center",
    "& div": {
      height: 160,
      padding: "0 0 0 16px",
      display: "flex",
      alignItems: "center",
      "&:nth-child(4n + 2)": {
        flexDirection: "column",
        justifyContent: "center",
        flex: 1,
      },
    },
    "& img": {
      maxWidth: 160,
      maxHeight: 160,
      border: `1px solid ${theme.palette.grey[500]}`,
      borderRadius: "12px",
    },
    "& h2": {
      fontSize: "48px",
      lineHeight: "60px",
      color: theme.palette.common.black,
      textAlign: "left",
      width: "100%",
    },
    "& p": {
      fontSize: "36px",
      lineHeight: "48px",
      color: theme.palette.common.black,
      textLlign: "left",
      width: "100%",
    },
    "& a": {
      display: "inline-block",
      minWidth: "256px",
      padding: "0 10px",
      height: 140,
      border: `1px solid #3375e0`,
      lineHeight: "144px",
      fontSize: "48px",
      textAlign: "center",
      color: theme.palette.primary.main,
      borderRadius: "2px",
    },
    "& span": {
      display: "block",
      width: 32,
      height: 32,
      fontSize: 24,
      color: theme.palette.common.black,
    },
  },
  tip_action: {
    margin: "24px",
    display: "flex",
    "& button": {
      ...theme.typography.button,
      height: 32,
      flex: 1,
      margin: "0 16px",
      color: theme.palette.common.white,
    },
  },
  tip_content: {
    padding: "0 24px !important",
    ...theme.typography.body2,
    color: theme.palette.grey[800],
    fontSize: 14,
    lineHeight: "20px",
    "& a": {
      color: theme.palette.primary.main,
    },
  },
  tip_dialog: {
    "& >div": {
      maxWidth: 400,
      paddingTop: 24,
    },
  },
  version: {
    height: 40,
    background: theme.palette.primary.main,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    "& div": {
      background: theme.palette.primary.light,
      borderRadius: 12,
      height: 22,
    },
    "& span": {
      display: "inline-block",
      lineHeight: "22px",
      color: theme.palette.primary.contrastText,
      padding: "0 20px",
      borderRight: `1px solid ${theme.palette.grey[50]}`,
    },
    "& i": {
      display: "inline-block",
      lineHeight: "22px",
      color: theme.palette.secondary.main,
      padding: "0 20px",
    },
  },
});
